import { useState } from 'react';
import { Bot, MessageCircle, Send, Sparkles, Trash2, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import api, { messageFrom } from '../services/api';

const prompts = { buyer: ['Show me vegetables under ₹50', 'What are my recent orders?', 'Recommend fresh produce'], farmer: ['Which products are low in stock?', 'How are my sales?', 'Which product sells the most?'], admin: ['What is marketplace revenue?', 'Which products sell the most?', 'Show marketplace statistics'] };
export default function AiAssistant() {
  const { user } = useAuth(); const [open, setOpen] = useState(false); const [messages, setMessages] = useState([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  if (!user) return null;
  const send = async text => { const message = (text || input).trim(); if (!message || loading) return; setMessages(current => [...current, { type: 'user', text: message }]); setInput(''); setError(''); setLoading(true); try { const { data } = await api.post('/ai/chat', { message }); setMessages(current => [...current, { type: 'assistant', text: data.message, data: data.data }]); } catch (e) { setError(messageFrom(e)); } finally { setLoading(false); } };
  return <div className="fixed bottom-5 right-5 z-40"><button aria-label="Open AgriLink AI" onClick={() => setOpen(value => !value)} className="btn-primary h-14 w-14 rounded-full p-0 shadow-lg shadow-leaf-900/25"><Bot size={24} /></button>{open && <section className="absolute bottom-16 right-0 flex h-[min(38rem,75vh)] w-[min(24rem,calc(100vw-2.5rem))] flex-col overflow-hidden rounded-3xl border border-leaf-100 bg-white shadow-2xl"><header className="flex items-center justify-between bg-leaf-700 px-4 py-4 text-white"><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/15"><Sparkles size={18} /></span><div><h2 className="font-bold">AgriLink AI</h2><p className="text-xs text-leaf-100">Grounded in your marketplace data</p></div></div><div className="flex gap-1"><button aria-label="Clear conversation" onClick={() => { setMessages([]); setError(''); }} className="rounded-lg p-2 hover:bg-white/10"><Trash2 size={16} /></button><button aria-label="Close AgriLink AI" onClick={() => setOpen(false)} className="rounded-lg p-2 hover:bg-white/10"><X size={18} /></button></div></header><div className="flex-1 space-y-3 overflow-y-auto bg-stone-50 p-4">{messages.length === 0 && <><div className="rounded-2xl bg-white p-3 text-sm leading-relaxed shadow-sm">Hi {user.name.split(' ')[0]} — ask me about verified products, your orders, or marketplace insights.</div><p className="pt-2 text-xs font-bold uppercase tracking-wide text-stone-500">Try asking</p><div className="flex flex-wrap gap-2">{prompts[user.role].map(prompt => <button key={prompt} onClick={() => send(prompt)} className="rounded-full border border-leaf-200 bg-white px-3 py-2 text-left text-xs font-medium text-leaf-700 hover:bg-leaf-50">{prompt}</button>)}</div></>}{messages.map((message, index) => <div key={`${message.type}-${index}`} className={`max-w-[90%] rounded-2xl px-3 py-2.5 text-sm leading-relaxed ${message.type === 'user' ? 'ml-auto bg-leaf-700 text-white' : 'bg-white text-stone-700 shadow-sm'}`}>{message.text}</div>)}{loading && <div className="flex items-center gap-2 rounded-2xl bg-white px-3 py-2.5 text-sm text-stone-500 shadow-sm"><MessageCircle size={15} className="animate-pulse text-leaf-600" /> AgriLink AI is thinking…</div>}{error && <div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}</div><form className="flex gap-2 border-t border-stone-200 bg-white p-3" onSubmit={event => { event.preventDefault(); send(); }}><input aria-label="Ask AgriLink AI" value={input} onChange={event => setInput(event.target.value)} placeholder="Ask AgriLink AI…" className="field mt-0 min-w-0 flex-1" maxLength="1000" /><button disabled={loading || !input.trim()} className="btn-primary px-3" aria-label="Send message"><Send size={18} /></button></form></section>}</div>;
}
