import { Link, NavLink, useNavigate } from 'react-router-dom';
import { Leaf, ShoppingCart, LayoutDashboard, LogOut } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import AiAssistant from './AiAssistant';

export default function Layout({ children }) {
  const { user, signOut } = useAuth(); const navigate = useNavigate();
  const logout = () => { signOut(); navigate('/'); };
  return <><header className="sticky top-0 z-20 border-b border-stone-200 bg-white/95 backdrop-blur"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-2 px-4"><Link to="/" className="flex shrink-0 items-center gap-2 text-xl font-bold text-leaf-700"><span className="grid h-9 w-9 place-items-center rounded-xl bg-leaf-100"><Leaf size={20} /></span><span>AgriLink</span></Link><nav className="flex items-center gap-1 overflow-x-auto text-sm font-medium"><NavLink to="/marketplace" className="whitespace-nowrap rounded-lg px-2 py-2 hover:bg-stone-100 sm:px-3">Marketplace</NavLink>{user?.role === 'buyer' && <NavLink to="/dashboard?tab=orders" className="whitespace-nowrap rounded-lg px-2 py-2 hover:bg-stone-100 sm:px-3">My orders</NavLink>}{user && <NavLink to="/dashboard" className="whitespace-nowrap rounded-lg px-2 py-2 hover:bg-stone-100 sm:px-3"><LayoutDashboard className="inline sm:mr-1" size={16} /><span className="hidden sm:inline">Dashboard</span></NavLink>}{user?.role === 'buyer' && <NavLink to="/cart" aria-label="Cart" className="rounded-lg px-2 py-2 hover:bg-stone-100 sm:px-3"><ShoppingCart className="inline" size={17} /></NavLink>}{user ? <button onClick={logout} className="whitespace-nowrap rounded-lg px-2 py-2 hover:bg-stone-100 sm:px-3"><LogOut className="inline sm:mr-1" size={16} /><span className="hidden sm:inline">Sign out</span></button> : <><NavLink to="/login" className="whitespace-nowrap rounded-lg px-2 py-2 hover:bg-stone-100 sm:px-3">Sign in</NavLink><NavLink to="/register" className="btn-primary whitespace-nowrap px-3 py-2">Join AgriLink</NavLink></>}</nav></div></header><main>{children}</main><AiAssistant /><footer className="mt-16 border-t border-stone-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-7 text-sm text-stone-500">© 2026 AgriLink · Direct, transparent agricultural trade.</div></footer></>;
}
