import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import api, { messageFrom } from '../services/api';

const initialAddress = (user) => ({ name: user?.name || '', phone: user?.phone || '', line1: user?.address?.line1 || '', city: user?.address?.city || '', state: user?.address?.state || '', pincode: user?.address?.pincode || '' });

export default function Cart() {
  const { user } = useAuth(); const [cart, setCart] = useState(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [address, setAddress] = useState(() => initialAddress(user)); const nav = useNavigate();
  const load = () => api.get('/cart').then(({ data }) => setCart(data.cart)).catch(e => setError(messageFrom(e)));
  useEffect(() => { load(); }, []);
  const groups = useMemo(() => { const map = {}; (cart?.items || []).filter(item => item.product?.farmer).forEach(item => { const id = item.product.farmer._id; (map[id] ??= []).push(item); }); return Object.values(map); }, [cart]);
  const update = (item, quantity) => api.patch(`/cart/items/${item._id}`, { quantity: Number(quantity) }).then(({ data }) => setCart(data.cart)).catch(e => setError(messageFrom(e)));
  const remove = id => api.delete(`/cart/items/${id}`).then(({ data }) => setCart(data.cart)).catch(e => setError(messageFrom(e)));
  const checkout = async (items) => { if (Object.values(address).some(value => !String(value).trim())) return setError('Please complete your delivery address before placing an order.'); if (!confirm('Place this order?')) return; setBusy(true); setError(''); try { await api.post('/orders', { items: items.map(item => ({ productId: item.product._id, quantity: item.quantity })), deliveryAddress: address }); await load(); nav('/dashboard?tab=orders'); } catch (e) { setError(messageFrom(e)); } finally { setBusy(false); } };
  if (!cart) return <p className="p-16 text-center">Loading your cart…</p>;
  return <div className="mx-auto max-w-4xl px-4 py-10"><h1 className="text-3xl font-bold">Your cart</h1><p className="mt-1 text-stone-500">Orders are grouped by farmer to keep transactions direct.</p>{error && <p className="mt-4 rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{groups.length === 0 ? <div className="panel mt-7 p-12 text-center">Your cart is empty.</div> : <><section className="panel mt-6 p-5"><h2 className="font-bold">Delivery address</h2><p className="mt-1 text-sm text-stone-500">This information is shared with the farmer for fulfilment.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[['name','Full name'],['phone','Phone'],['line1','Address'],['city','City'],['state','State'],['pincode','Pincode']].map(([field,label]) => <label key={field} className={`label ${field === 'line1' ? 'sm:col-span-2' : ''}`}>{label}<input required className="field" value={address[field]} onChange={event => setAddress(current => ({ ...current, [field]: event.target.value }))} /></label>)}</div></section><div className="mt-6 space-y-5">{groups.map(items => { const total = items.reduce((sum, item) => sum + item.product.price * item.quantity, 0); return <section key={items[0].product.farmer._id} className="panel p-5"><div className="flex justify-between"><h2 className="font-bold">From {items[0].product.farmer.name}</h2><span className="font-bold text-leaf-700">₹{total.toLocaleString()}</span></div><div className="mt-4 divide-y">{items.map(item => <div key={item._id} className="flex items-center gap-3 py-3"><div className="grid h-10 w-10 place-items-center rounded bg-leaf-50">🌾</div><div className="flex-1"><b>{item.product.name}</b><p className="text-sm text-stone-500">₹{item.product.price}/{item.product.unit}</p></div><input className="field mt-0 w-20" type="number" min="1" max={item.product.availableQuantity} value={item.quantity} onChange={event => update(item, event.target.value)} /><button onClick={() => remove(item._id)} className="text-sm font-semibold text-red-600">Remove</button></div>)}</div><button disabled={busy} onClick={() => checkout(items)} className="btn-primary mt-4 w-full">{busy ? 'Placing order…' : `Place order · ₹${total.toLocaleString()}`}</button></section>; })}</div></>}</div>;
}
